--- 
before_install: 
  - "sudo apt-get update"
  - "sudo apt-get install shellcheck"
  - "sudo apt-get install imagemagick"
  - "sudo apt install p7zip-full"
  - "sudo apt install ghostscript"
  - "ls -l"
  - "sudo apt-get install ghostscript"
  - "sudo apt install p7zip-full"
language: bash
notifications: 
  email: 
    on_success: never
scirpt: 
  - "wget \"https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/worldcupplayerinfo.tsv\""
  - "wget \"https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z\""
  - "7z x -oweb_log.tsv web_log.tsv.7z"
  - "ls -l"
  - "cd chap0x04/"
  - "ls -l"
  - "echo \"Task one\""
  - "shellcheck bash/scripts.sh"
  - "echo \":===================================\""
  - "cd test_pics/"
  - "bash ../bash/scripts.sh -h"
  - "ls -l"
  - "bash ../bash/scripts.sh -q 88%"
  - "ls -l"
  - "bash ../bash/scripts.sh -r 70%"
  - "ls -l"
  - "bash ../bash/scripts.sh -w JiJi"
  - "ls -l"
  - "bash ../bash/scripts.sh -p \"JiJi's pics\""
  - "ls -l"
  - "bash ../bash/scripts.sh -t"
  - "ls -l"
  - "cd ../../"
  - "ls -l"
  - "echo \":===================================\""
  - "echo \"Task two\""
  - "shellcheck chap0x04/bash/scripts2.sh"
  - "echo \":===================================\""
  - "bash chap0x04/bash/scripts2.sh -h"
  - "bash chap0x04/bash/scripts2.sh -r"
  - "bash chap0x04/bash/scripts2.sh -p"
  - "bash chap0x04/bash/scripts2.sh -n"
  - "bash chap0x04/bash/scripts2.sh -a"
  - "echo \":===================================:\""
  - "echo \"Task three\""
  - "shellcheck chap0x04/bash/scripts3.sh"
  - "echo \":===================================:\""
  - "bash chap0x04/bash/scripts3.sh -h"
  - "bash chap0x04/bash/scripts3.sh -t"
  - "bash chap0x04/bash/scripts3.sh -i"
  - "bash chap0x04/bash/scripts3.sh -u"
  - "bash chap0x04/bash/scripts3.sh -r"
  - "bash chap0x04/bash/scripts3.sh -x"
  - "bash chap0x04/bash/scripts3.sh -s /icons/menu.xbm"
